### ISSUE TITLE
Help convert BancorFormula.js tests to Embark

### ISSUE THREAD

**Issue by andytudhope** [status-im/discover-dapps#14]
Though The DApp Store implements the BancorFormula.sol contract as is, it only implements the mathematical functions and, as such, we should test it again. Also, it's good to have a full test suite in Embark, rather than relying on Bancor's tests as proof of the contract's correctness. The tests I am converting are here:

https://github.com/bancorprotocol/contracts/blob/master/solidity/test/BancorFormula.js

You can see my current attempts on this branch:

https://github.com/status-im/discover-dapps/tree/embark/test

## Issues I've run into so far

1. Though I have the same version of web3-utils and ethereumjs-utils as Bancor in `package.json`, the first error I get is `web3.toBigNumber() is not a function`, hence the change to `web3.utils.toBN`.

2. This change, however, cause a lot of other changes as `web3.utils.toBN().toPower() is not a function` etc.

3. I'm not sure how to emulate `plus()`, `minus()`, `times()` and `dividedToIntegerBy()` in Embark, so have gone for the normal signs, but am unsure they yield exactly the same values.

4. I **think** that, with Embark, I should be using `.call()` for all the contract calls, but that causes them all to fail, as `baseN` is not a valid number to pass in.

5. I've taken the exact `catchRevert()` util as Bancor uses, but am unsure if Embark handles reverts in the same way, and would prefer to use `assertReverts()` from `testUtils.js` if possible.

**Comment by corpetty** [comment]
w.r.t 3: I don't think using normal signs will yield same results. Aren't these BN class functions?

**Comment by holiman** [comment]
I _think_ that there is even more test coverage from the python side than from the js-side: https://github.com/bancorprotocol/contracts/tree/master/solidity/python

**Comment by corpetty** [comment]
> w.r.t 3: I don't think using normal signs will yield same results. Aren't these BN class functions?

Do these not work?   If not, we should bring it up with embark people, as they expose the same web3 object, at least that's what the docs say. 

https://web3js.readthedocs.io/en/1.0/web3-utils.html

**Comment by corpetty** [comment]
This should help with the BN API, I've gotten the first commented block to work. 

https://github.com/indutny/bn.js/

**Comment by andytudhope** [comment]
Solved by https://github.com/status-im/discover-dapps/commit/2889281dbb92510e14d73ad11a31311555dded34
