### ISSUE TITLE
Automate deployment on github.io

### ISSUE THREAD

**Issue by jeluard** [status-im/discover-dapps#2]
Use CircleCI or similar to automate the deployment of `master` branch on [Github Pages](https://pages.github.com/)

**Comment by andytudhope** [comment]
We can likely automate with our own Jenkins stuff when this is ready, which is when I will ping Jakub.

**Comment by jeluard** [comment]
Why when this is ready? We can do it now and enjoy watching real-time progress!

@JamesGarethSmith WDYT?
