### ISSUE TITLE
Change text to indicate that Submit a Dapp option will be implemented in future versions or remove this item

### ISSUE THREAD

**Issue by annadanchenko** [status-im/discover-dapps#35]
if tap on Android on Submit a Dapp nothing happens (Android, release build 2 for 0.12.0 release)

Users would expect that every option is functional, this one is expected to be implemented in future versions, so we need to indicate it in the text or remove this option.

![Screenshot_20190425-181524](https://user-images.githubusercontent.com/6584810/56752371-650bdc00-6788-11e9-86ff-811ef479f8df.png)

Steps:
- open dap.ps in status app
- scroll to the end of the page

**Comment by rachelhamlin** [comment]
Don't know what this particular screen looks like but is it possible to simply remove?

**Comment by hesterbruikman** [comment]
Looks like it's just a list item, so should be easy enough to remove for now. Imagine though that maybe @andytudhope had something in mind for some sort of manual pre-submission.

**Comment by annadanchenko** [comment]
updated description with picture and steps. Agree that removing this item can also help

**Comment by andytudhope** [comment]
Fixed in https://github.com/status-im/discover-dapps/commit/98844b7c5a0f541e09963dbbf63b3980a612aa60

**Comment by rachelhamlin** [comment]
Thanks for doing that @andytudhope.
